"use client";

import { useEffect, useState } from "react";

type SettingsResponse = { version: number; source: string; settings: { missionBudgets: Record<string, number>; contactEnrichment: Record<string, number | boolean>; interface: { defaultMissionPreset: string; showAdvancedMissionSettings: boolean } } };
const presets: Record<string, Record<string, number>> = { CONSERVATIVE: { maxCandidateAccounts: 5, maxSearches: 12, maxPages: 20, maxModelCalls: 20, maxCostUsd: 2 }, STANDARD: { maxCandidateAccounts: 10, maxSearches: 24, maxPages: 40, maxModelCalls: 40, maxCostUsd: 5 }, DEEP: { maxCandidateAccounts: 20, maxSearches: 50, maxPages: 80, maxModelCalls: 100, maxCostUsd: 15 } };

export function SettingsPage() {
  const [data, setData] = useState<SettingsResponse | null>(null); const [draft, setDraft] = useState<Record<string, number>>({}); const [preset, setPreset] = useState("CONSERVATIVE"); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => {
    void fetch("/api/settings", { cache: "no-store" })
      .then((response) => response.json() as Promise<SettingsResponse>)
      .then((payload) => { setData(payload); setDraft(payload.settings.missionBudgets); setPreset(payload.settings.interface.defaultMissionPreset); })
      .catch((reason) => setError(reason instanceof Error ? reason.message : "Settings could not be loaded."));
  }, []);
  function applyPreset(value: string) { setPreset(value); if (presets[value]) setDraft(presets[value]); }
  async function save() { if (!data) return; setMessage(""); setError(""); const response = await fetch("/api/settings", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ version: data.version, patch: { missionBudgets: draft, interface: { ...data.settings.interface, defaultMissionPreset: preset } }, changeSummary: `Mission budget preset changed to ${preset}` }) }); const payload = await response.json() as SettingsResponse & { error?: { message?: string } }; if (!response.ok) { setError(payload.error?.message ?? "Settings could not be saved."); return; } setData(payload); setMessage(`Saved settings version ${payload.version}.`); }
  if (!data) return <section><h1 className="text-4xl font-black">Settings</h1><p className="mt-3 text-white/50">Loading operational defaults…</p></section>;
  return <section className="max-w-4xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#f5c542]">Operational control</p><h1 className="mt-2 text-4xl font-black">Settings</h1><p className="mt-3 max-w-2xl text-white/55">Persistent defaults apply to new missions. Absolute safety ceilings remain code-controlled and cannot be raised here.</p><div className="mt-8 grid gap-6 md:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><h2 className="text-lg font-bold">Mission preset</h2><label className="mt-4 block text-sm text-white/60">Default preset<select value={preset} onChange={(event) => applyPreset(event.target.value)} className="mt-2 w-full rounded-xl border border-white/15 bg-black/20 px-3 py-3 text-white"><option>CONSERVATIVE</option><option>STANDARD</option><option>DEEP</option><option>CUSTOM</option></select></label><p className="mt-4 text-xs leading-5 text-white/45">Version {data.version || "bootstrap"} · source {data.source}</p></div><div className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><h2 className="text-lg font-bold">Mission budget</h2><div className="mt-4 grid grid-cols-2 gap-3">{Object.entries(draft).map(([key, value]) => <label key={key} className="text-xs text-white/55">{key.replace(/^max/, "Max ")}<input type="number" min="0" value={value} onChange={(event) => { setPreset("CUSTOM"); setDraft((current) => ({ ...current, [key]: Number(event.target.value) })); }} className="mt-1 w-full rounded-xl border border-white/15 bg-black/20 px-3 py-2 text-white" /></label>)}</div><p className="mt-4 text-xs text-white/45">Absolute ceilings: 25 accounts, 100 searches, 100 pages, 200 model calls, $100 per mission.</p></div></div>{error ? <p className="mt-5 rounded-xl border border-red-400/30 bg-red-500/10 p-3 text-sm text-red-200" role="alert">{error}</p> : null}{message ? <p className="mt-5 rounded-xl border border-emerald-400/30 bg-emerald-500/10 p-3 text-sm text-emerald-200" role="status">{message}</p> : null}<button onClick={() => void save()} className="mt-6 rounded-full border border-[#f5c542]/50 px-6 py-3 text-sm font-bold text-[#f5c542]">Save settings</button></section>;
}
